### ISSUE TITLE
Me gustaría publicar en el blog. 

### ISSUE THREAD

**Issue by LaurenceM10** [js-ni/blog-api#2]
Hola.  
Mi nombre es Laurence. 
Me gustaría publicar en el blog.  
Mi correo electrónico es laurenmontenegro10@gmail.com.  
Mi usuario en medium es @laurenmontenegro10.  

Saludos.

**Comment by paulomcnally** [comment]
@LaurenceM10 tenes que rellenar la plantilla, para saber tu correo y username de medium.

**Comment by LaurenceM10** [comment]
Ya.

**Comment by paulomcnally** [comment]
Revisa porfa @LaurenceM10 https://medium.com/javascript-nicaragua
