### ISSUE TITLE
Quiero publicar en el blog

### ISSUE THREAD

**Issue by juanpicado** [js-ni/blog-api#3]
Hola.

Mi nombre es Juan.

Me gustaría publicar en el blog.

Mi correo electrónico es juanpicado19@gmail.com

Mi usuario en medium es jotadeveloper.

Saludos.

**Comment by paulomcnally** [comment]
Estoy desde el móvil, no me da la opción de agregarte. Mañana a penas esté en la PC te agrego.

**Comment by paulomcnally** [comment]
Listo @juanpicado.

**Comment by juanpicado** [comment]
Y donde se publica ? No me aparece ninguna publicación nueva en médium

**Comment by paulomcnally** [comment]
Desde https://medium.com/javascript-nicaragua/new-story
